export const aiCourses = [
  {
    id: 1,
    title: "The AI Engineer Course 2025: Complete AI Engineer Bootcamp",
    author: "365 Careers",
    rating: 4.6,
    reviews: 801,
    price: "E£349.99",
    originalPrice: "E£1,599.99",
    badge: "Bestseller",
    duration: "42 hours",
  },
  {
    id: 2,
    title: "Intro to AI Agents and Agentic AI",
    author: "365 Careers",
    rating: 4.4,
    reviews: 595,
    price: "E£349.99",
    originalPrice: "E£1,599.99",
    badge: "Bestseller",
    duration: "18 hours",
  },
  {
    id: 3,
    title: "Artificial Intelligence (AI) Foundations for Developers",
    author: "Rahul Rajal Singh",
    rating: 5.0,
    reviews: 21,
    price: "E£349.99",
    originalPrice: "E£1,599.99",
    badge: "Highest Rated",
    duration: "25 hours",
  },
  {
    id: 4,
    title: "The Complete Guide To AI Powered Salesforce Development",
    author: "Matt Gerry",
    rating: 4.8,
    reviews: 74,
    price: "E£349.99",
    originalPrice: "E£1,599.99",
    badge: "Hot & New",
    duration: "31 hours",
  },
];

export const categories = [
  "Artificial Intelligence (AI)",
  "Python",
  "Microsoft Excel",
  "AI Agents & Agentic AI",
  "Digital Marketing",
  "Amazon AWS",
  "Web Development",
  "Data Science",
];
